/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    companies: Company;
    accounts: Account;
    wallets: Wallet;
    faqs: Faq;
    locations: Location;
    contracts: Contract;
    meta: Meta;
    assetTypes: AssetType;
    assets: Asset;
    passMetas: PassMeta;
    passes: Pass;
    contacts: Contact;
    assetReasons: AssetReason;
    customers: Customer;
  };
  globals: {};
}
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  avatarUrl?: string;
  company?: string | Company;
  title: string;
  jobRole: 'asset_manager' | 'property_manager' | 'fund_manager' | 'auditor' | 'engineer' | 'other';
  wallet?: string | Wallet;
  userSecret: string;
  roles?: ('admin' | 'manager' | 'editor' | 'membership_manager' | 'viewer')[];
  assetRoles?: ('asset_editor' | 'asset_manager' | 'supply_manager')[];
  distributionRoles?: ('dist_escrow' | 'dist_admin')[];
  isRedcMember?: boolean;
  isFoundationMember?: boolean;
  isSystem?: boolean;
  services?: ('moralis' | 'gcp' | 'blockchain' | 'cybavo')[];
  enableAPIKey?: boolean;
  apiKey?: string;
  apiKeyIndex?: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Company {
  id: string;
  regCode: string;
  name: string;
  avatarUrl?: string;
  regCountry:
    | 'AF'
    | 'AX'
    | 'AL'
    | 'DZ'
    | 'AS'
    | 'AD'
    | 'AO'
    | 'AI'
    | 'AQ'
    | 'AG'
    | 'AR'
    | 'AM'
    | 'AW'
    | 'AU'
    | 'AT'
    | 'AZ'
    | 'BS'
    | 'BH'
    | 'BD'
    | 'BB'
    | 'BY'
    | 'BE'
    | 'BZ'
    | 'BJ'
    | 'BM'
    | 'BT'
    | 'BO'
    | 'BA'
    | 'BW'
    | 'BV'
    | 'BR'
    | 'IO'
    | 'BN'
    | 'BG'
    | 'BF'
    | 'BI'
    | 'KH'
    | 'CM'
    | 'CA'
    | 'CV'
    | 'KY'
    | 'CF'
    | 'TD'
    | 'CL'
    | 'CN'
    | 'CX'
    | 'CC'
    | 'CO'
    | 'KM'
    | 'CG'
    | 'CD'
    | 'CK'
    | 'CR'
    | 'CI'
    | 'HR'
    | 'CU'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'DJ'
    | 'DM'
    | 'DO'
    | 'EC'
    | 'EG'
    | 'SV'
    | 'GQ'
    | 'ER'
    | 'EE'
    | 'ET'
    | 'FK'
    | 'FO'
    | 'FJ'
    | 'FI'
    | 'FR'
    | 'GF'
    | 'PF'
    | 'TF'
    | 'GA'
    | 'GM'
    | 'GE'
    | 'DE'
    | 'GH'
    | 'GI'
    | 'GR'
    | 'GL'
    | 'GD'
    | 'GP'
    | 'GU'
    | 'GT'
    | 'GG'
    | 'GN'
    | 'GW'
    | 'GY'
    | 'HT'
    | 'HM'
    | 'VA'
    | 'HN'
    | 'HK'
    | 'HU'
    | 'IS'
    | 'IN'
    | 'ID'
    | 'IR'
    | 'IQ'
    | 'IE'
    | 'IM'
    | 'IL'
    | 'IT'
    | 'JM'
    | 'JP'
    | 'JE'
    | 'JO'
    | 'KZ'
    | 'KE'
    | 'KI'
    | 'KP'
    | 'KR'
    | 'KW'
    | 'KG'
    | 'LA'
    | 'LV'
    | 'LB'
    | 'LS'
    | 'LR'
    | 'LY'
    | 'LI'
    | 'LT'
    | 'LU'
    | 'MO'
    | 'MK'
    | 'MG'
    | 'MW'
    | 'MY'
    | 'MV'
    | 'ML'
    | 'MT'
    | 'MH'
    | 'MQ'
    | 'MR'
    | 'MU'
    | 'YT'
    | 'MX'
    | 'FM'
    | 'MD'
    | 'MC'
    | 'MN'
    | 'ME'
    | 'MS'
    | 'MA'
    | 'MZ'
    | 'MM'
    | 'NA'
    | 'NR'
    | 'NP'
    | 'NL'
    | 'AN'
    | 'NC'
    | 'NZ'
    | 'NI'
    | 'NE'
    | 'NG'
    | 'NU'
    | 'NF'
    | 'MP'
    | 'NO'
    | 'OM'
    | 'PK'
    | 'PW'
    | 'PS'
    | 'PA'
    | 'PG'
    | 'PY'
    | 'PE'
    | 'PH'
    | 'PN'
    | 'PL'
    | 'PT'
    | 'PR'
    | 'QA'
    | 'RE'
    | 'RO'
    | 'RU'
    | 'RW'
    | 'SH'
    | 'KN'
    | 'LC'
    | 'PM'
    | 'VC'
    | 'WS'
    | 'SM'
    | 'ST'
    | 'SA'
    | 'SN'
    | 'RS'
    | 'SC'
    | 'SL'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'SB'
    | 'SO'
    | 'ZA'
    | 'GS'
    | 'ES'
    | 'LK'
    | 'SD'
    | 'SR'
    | 'SJ'
    | 'SZ'
    | 'SE'
    | 'CH'
    | 'SY'
    | 'TW'
    | 'TJ'
    | 'TZ'
    | 'TH'
    | 'TL'
    | 'TG'
    | 'TK'
    | 'TO'
    | 'TT'
    | 'TN'
    | 'TR'
    | 'TM'
    | 'TC'
    | 'TV'
    | 'UG'
    | 'UA'
    | 'AE'
    | 'GB'
    | 'US'
    | 'UM'
    | 'UY'
    | 'UZ'
    | 'VU'
    | 'VE'
    | 'VN'
    | 'VG'
    | 'VI'
    | 'WF'
    | 'EH'
    | 'YE'
    | 'ZM'
    | 'ZW';
  vatNumber?: string;
  type: 'holding' | 'spv' | 'fund' | 'reit' | 'bank' | 'other';
  location?: string[] | Location[];
  ubos?: string[] | Company[];
  foundedOn?: string;
  website?: string;
  bankAccounts?: string[] | Account[];
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Location {
  id: string;
  fullAddress: string;
  country:
    | 'AF'
    | 'AX'
    | 'AL'
    | 'DZ'
    | 'AS'
    | 'AD'
    | 'AO'
    | 'AI'
    | 'AQ'
    | 'AG'
    | 'AR'
    | 'AM'
    | 'AW'
    | 'AU'
    | 'AT'
    | 'AZ'
    | 'BS'
    | 'BH'
    | 'BD'
    | 'BB'
    | 'BY'
    | 'BE'
    | 'BZ'
    | 'BJ'
    | 'BM'
    | 'BT'
    | 'BO'
    | 'BA'
    | 'BW'
    | 'BV'
    | 'BR'
    | 'IO'
    | 'BN'
    | 'BG'
    | 'BF'
    | 'BI'
    | 'KH'
    | 'CM'
    | 'CA'
    | 'CV'
    | 'KY'
    | 'CF'
    | 'TD'
    | 'CL'
    | 'CN'
    | 'CX'
    | 'CC'
    | 'CO'
    | 'KM'
    | 'CG'
    | 'CD'
    | 'CK'
    | 'CR'
    | 'CI'
    | 'HR'
    | 'CU'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'DJ'
    | 'DM'
    | 'DO'
    | 'EC'
    | 'EG'
    | 'SV'
    | 'GQ'
    | 'ER'
    | 'EE'
    | 'ET'
    | 'FK'
    | 'FO'
    | 'FJ'
    | 'FI'
    | 'FR'
    | 'GF'
    | 'PF'
    | 'TF'
    | 'GA'
    | 'GM'
    | 'GE'
    | 'DE'
    | 'GH'
    | 'GI'
    | 'GR'
    | 'GL'
    | 'GD'
    | 'GP'
    | 'GU'
    | 'GT'
    | 'GG'
    | 'GN'
    | 'GW'
    | 'GY'
    | 'HT'
    | 'HM'
    | 'VA'
    | 'HN'
    | 'HK'
    | 'HU'
    | 'IS'
    | 'IN'
    | 'ID'
    | 'IR'
    | 'IQ'
    | 'IE'
    | 'IM'
    | 'IL'
    | 'IT'
    | 'JM'
    | 'JP'
    | 'JE'
    | 'JO'
    | 'KZ'
    | 'KE'
    | 'KI'
    | 'KP'
    | 'KR'
    | 'KW'
    | 'KG'
    | 'LA'
    | 'LV'
    | 'LB'
    | 'LS'
    | 'LR'
    | 'LY'
    | 'LI'
    | 'LT'
    | 'LU'
    | 'MO'
    | 'MK'
    | 'MG'
    | 'MW'
    | 'MY'
    | 'MV'
    | 'ML'
    | 'MT'
    | 'MH'
    | 'MQ'
    | 'MR'
    | 'MU'
    | 'YT'
    | 'MX'
    | 'FM'
    | 'MD'
    | 'MC'
    | 'MN'
    | 'ME'
    | 'MS'
    | 'MA'
    | 'MZ'
    | 'MM'
    | 'NA'
    | 'NR'
    | 'NP'
    | 'NL'
    | 'AN'
    | 'NC'
    | 'NZ'
    | 'NI'
    | 'NE'
    | 'NG'
    | 'NU'
    | 'NF'
    | 'MP'
    | 'NO'
    | 'OM'
    | 'PK'
    | 'PW'
    | 'PS'
    | 'PA'
    | 'PG'
    | 'PY'
    | 'PE'
    | 'PH'
    | 'PN'
    | 'PL'
    | 'PT'
    | 'PR'
    | 'QA'
    | 'RE'
    | 'RO'
    | 'RU'
    | 'RW'
    | 'SH'
    | 'KN'
    | 'LC'
    | 'PM'
    | 'VC'
    | 'WS'
    | 'SM'
    | 'ST'
    | 'SA'
    | 'SN'
    | 'RS'
    | 'SC'
    | 'SL'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'SB'
    | 'SO'
    | 'ZA'
    | 'GS'
    | 'ES'
    | 'LK'
    | 'SD'
    | 'SR'
    | 'SJ'
    | 'SZ'
    | 'SE'
    | 'CH'
    | 'SY'
    | 'TW'
    | 'TJ'
    | 'TZ'
    | 'TH'
    | 'TL'
    | 'TG'
    | 'TK'
    | 'TO'
    | 'TT'
    | 'TN'
    | 'TR'
    | 'TM'
    | 'TC'
    | 'TV'
    | 'UG'
    | 'UA'
    | 'AE'
    | 'GB'
    | 'US'
    | 'UM'
    | 'UY'
    | 'UZ'
    | 'VU'
    | 'VE'
    | 'VN'
    | 'VG'
    | 'VI'
    | 'WF'
    | 'EH'
    | 'YE'
    | 'ZM'
    | 'ZW';
  municipality: string;
  streetName: string;
  buildingNr: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  geocoordinates?: [number, number];
  locationId?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Account {
  id: string;
  accountNr: string;
  bank: string | Company;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Wallet {
  id: string;
  name: string;
  address: string;
  blockchain?: 'polygon' | 'ethereum' | 'moonbeam';
  environment?: 'production' | 'test';
  tag?: string;
  user?: string | User;
  externalName?: string;
  externalId: string;
  provider: 'metamask' | 'fireblocks' | 'Other';
  externalVaultId?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Faq {
  id: string;
  question: string;
  answer: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Contract {
  id: string;
  name: string;
  description?: string;
  address: string;
  blockchain?: 'polygon' | 'ethereum' | 'moonbeam';
  environment?: 'production' | 'test';
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Meta {
  id: string;
  Name?: string;
  actual?: boolean;
  headerImage?: string;
  avatarImage?: string;
  title: string;
  subtitle: string;
  description: string;
  totalNav?: number;
  nrOfAssets?: number;
  redcurrySupply?: number;
  daoSupply?: number;
  redcurryStakingYield?: number;
  daoStakingYield?: number;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface AssetType {
  type: string;
  typeCode?: number;
  subType: string;
  title: string;
  id: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Asset {
  cascade?: number;
  changeOperation?: string;
  id: string;
  supplyChanging: boolean;
  expectedSupplyDelta?: number;
  customer?: string | Customer;
  mintDirect?: boolean;
  closePosition?: boolean;
  recFromSale?: number;
  title: string;
  assetType: string | AssetType;
  description: string;
  comments?: string;
  location?: string | Location;
  imageUrl?: string;
  custodian?: string | Company;
  creationReason?: string | AssetReason;
  extRefUrl?: string;
  tags?: string;
  sourceAsset?: string | Asset;
  shares: {
    nrOfParts: number;
    pricePerPart: number;
    id?: string;
    blockName?: string;
    blockType: 'Share';
  }[];
  oav?: number;
  coa?: number;
  oavi?: number;
  oavr?: number;
  oa?: number;
  ral?: number;
  bd?: number;
  totalSupplyQty?: number;
  lastValuation?: string;
  valuationUrl?: string;
  lastValueAudit?: string;
  valueAuditUrl?: string;
  currency?: 'EUR' | 'UDS';
  userSignature?: string;
  collaborators?: string[] | User[];
  ownerhipType?: 'direct' | 'shares' | 'equity' | 'tokens' | 'other';
  immediateOwner?: string | Company;
  extOwnershipRefUrl?: string;
  onAccounts?: string | Account;
  ownershipPercentage: number;
  txnHash?: string;
  txnStateUpdatedAt?: number;
  txnId?: string;
  syncedOnChain?: boolean;
  eventId?: string;
  tokenId?: string;
  txnStatus?: string;
  statusReason?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Customer {
  id: string;
  name: string;
  product: 'redc' | 'curry';
  company?: string | Company;
  wallet: string | Wallet;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface AssetReason {
  id: string;
  reason: string;
  description: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface PassMeta {
  id: string;
  title: string;
  typeCode: string;
  description: string;
  imageUrl: string;
  maxSupply: number;
  canSupplyChange?: boolean;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Pass {
  id: string;
  userSignature: string;
  typeCode: '0' | '1' | '2' | '3';
  recipient: string | Contact;
  title?: string;
  description?: string;
  imgUrl?: string;
  signature?: string;
  transactionHash?: string;
  isMinted?: boolean;
  tokenId?: string;
  contractAdr?: string;
  openseaUrl?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Contact {
  id: string;
  email: string;
  walletAddress: string;
  firstName?: string;
  lastName?: string;
  telegramUsername?: string;
  discordUsername?: string;
  leadCapturedOn?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
